--- Kernel/sound/soc/codecs/Makefile
+++ Kernel/sound/soc/codecs/Makefile
@@ -50,9 +50,15 @@
 snd-soc-wm8988-objs := wm8988.o
 snd-soc-wm8990-objs := wm8990.o
 snd-soc-wm8993-objs := wm8993.o
-ifeq ($(CONFIG_SND_SOC_WM8994_VICTORY),y)
+ifeq ($(CONFIG_SND_SOC_WM8994_ARIES),y)
 snd-soc-wm8994-objs := wm8994_samsung.o wm8994_aries.o
 endif
+ifeq ($(CONFIG_SND_SOC_WM8994_CRESPO),y)
+snd-soc-wm8994-objs := crespo/wm8994_samsung.o crespo/wm8994_herring.o
+endif
+ifeq ($(CONFIG_SND_SOC_WM8994_VICTORY),y)
+snd-soc-wm8994-objs := victory/wm8994_samsung.o victory/wm8994_aries.o
+endif
 ifeq ($(CONFIG_SND_SOC_WM8994_ATLAS),y)
 ifeq ($(CONFIG_S5PV210_GARNETT_DELTA),y)
 snd-soc-wm8994-objs := garnett/wm8994_samsung.o garnett/wm8994_aries.o
